CREATE TABLE ROLE(
    ROLE_ID INTEGER GENERATED AS IDENTITY NOT NULL,
    ROLE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE USER(
    KLIENT_ID INTEGER GENERATED AS IDENTITY NOT NULL,
    FIRST_NAME VARCHAR(30),
    SURNAME VARCHAR(30),
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(50),
    LOGIN VARCHAR(30),
    PASSWORD VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    
    ROLE_ID INTEGER DEFAULT NULL,

    CONSTRAINT PK_KLIENT_ID PRIMARY KEY (KLIENT_ID),
    CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE
);

CREATE TABLE SPORT(
    SPORT_ID INTEGER GENERATED AS IDENTITY NOT NULL,
    SPORT_NAME VARCHAR(30) NOT NULL,
    NUMBER_OF_PLAYERS INTEGER NOT NULL
);

CREATE TABLE TEAM(
    TEAM_ID INTEGER GENERATED AS IDENTITY NOT NULL,
    TEAM_NAME VARCHAR(30) NOT NULL,
    LOGO_URL VARCHAR(255),
    NUMBER_OF_PLAYERS INTEGER DEFAULT 0
    MANAGER_ID INTEGER NOT NULL,

    CONSTRAINT FK_MANAGER_ID FOREIGN KEY (MANAGER_ID) REFERENCES USER
);

CREATE TABLE MEMBER_OF_TEAM(
    TEAM_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,

    CONSTRAINT FK_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAM,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER,
    CONSTRAINT PK_MEMBER_OF_TEAM_ID PRIMARY KEY(TEAM_ID, USER_ID)
);

CREATE TABLE MATCH(
    MATCH_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    RESULT VARCHAR(30),
    INDEX_OF_MATCH INTEGER NOT NULL,
    IS_FINISHED DECIMAL(1,0) DEFAULT 0,
    WINNER_ID INTEGER NULL,
    PARTICIPANT1_ID INTEGER NULL,
    PARTICIPANT2_ID INTEGER NULL,
    TOURNAMENT_ID INTEGER NOT NULL,

    CONSTRAINT PK_MATCH_ID PRIMARY KEY (MATCH_ID),
    CONSTRAINT FK_WINNER_ID FOREIGN KEY (WINNER_ID) REFERENCES PARTICIPANT,
    CONSTRAINT FK_PARTICIPANT1_ID FOREIGN KEY (PARTICIPANT1_ID) REFERENCES PARTICIPANT,
    CONSTRAINT FK_PARTICIPANT2_ID FOREIGN KEY (PARTICIPANT2_ID) REFERENCES PARTICIPANT
);

CREATE TABLE PARTICIPANT(
    PARTICIPANT_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    PARTICIPANT_NAME VARCHAR(30),
    IS_APPROVED DECIMAL(1,0) DEFAULT 0,
    PARTICIPANT_TYPE VARCHAR(6) NOT NULL CHECK(PARTICIPANT_TYPE IN ('team', 'user')),
    TEAM_ID INTEGER NULL,
    USER_ID INTEGER NULL,
    TOURNAMENT_ID INTEGER NOT NULL,

    CONSTRAINT PK_PARTICIPANT_ID PRIMARY KEY (PARTICIPANT_ID),
    CONSTRAINT FK_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAM,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER
);

CREATE TABLE TOURNAMENT(
    TOURNAMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    TOURNAMENT_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    START_DATE DATE NOT NULL,
    PRICEPOOL DECIMAL(20,2),
    IS_APPROVED DECIMAL(1,0) DEFAULT 0,
    NUMBER_OF_PARTICIPANTS INTEGER,
    MANAGER_ID INTEGER NOT NULL,
    SPORT_ID NOT NULL,

    CONSTRAINT PK_TOURNAMENT_ID PRIMARY KEY (TOURNAMENT_ID),
    CONSTRAINT FK_MANAGER_ID FOREIGN KEY (MANAGER_UD) REFERENCES USER,
    CONSTRAINT FK_SPORT_ID FOREIGN KEY (SPORT_ID) REFERENCES SPORT
);